# Assignment 3

## Instructions - Read this first!

This is an individual homework assignment. This means that:

- You may discuss the problems in this assignment with other students in this course and your instructor/TA, but YOUR WORK MUST BE YOUR OWN.
- Do not show other students code or your own work on this assignment.
- You may consult external references, but not actively receive help from individuals not involved in this course.
- Cite all references outside of the course you used, including conversations with other students which were helpful. (This helps us give credit where it is due!). All references must use a commonly accepted reference format, for example, APA or IEEE (or another citation style of your choice).

If any of these rules seem ambiguous, please check with with your instructor for help interpreting them.

We suggest completing this assignment using the provided notebook. Each question should be answered using a SQL query (or combination or SQL queries) unless the text indicates that you may (or should) do something else. You may submit your queries embedded in Python, using SQLAlchemy or the MySQL Connector, or as plain text in Markdown.

## When you submit your work

Your submission will be graded manually. To ensure that everything goes smoothly, please follow these instructions to prepare your notebook for submission to the D2L Dropbox for Assignment 3:

- Please remove any print statments used to test your work (you can comment them out)
- Please provide your solutions where asked; please do not alter any other parts of this notebook.
- If you need to add cells to test your code please move them to the end of the notebook before submission- or you may included your commented out answers and tests in the cells provided

## Introduction

In this assignment, you will continue to practice and extend your SQL skills, and compare your work to MongoDB.

We will be using two datasets from the City of Toronto's Open Data Portal. 

 * `earlyOn_info_geom4326.csv` lists locations participating in Ontario's EarlyON program. You can find out more about this dataset from the [City of Toronto's Open Data Portal](https://open.toronto.ca/dataset/earlyon-child-and-family-centres/)
 * `tdsb_info_geom4326.csv` lists all locations of schools that are operated by the Toronto District School Board. You can find out more about this dataset from the [City of Toronto's Open Data Portal](https://open.toronto.ca/dataset/toronto-district-school-board-locations/).
One dataset lists the locations participating in Ontario's EarlyON program.  

For those who are interested, both CSVs use the WGS84 projection for their location data.

Both datasets are licensed under the [Open Government License - Toronto](https://open.toronto.ca/open-data-license/).

You may want to look up both EarlyON and the Toronto District School Board, to acquire more context for this assignment.


## Data cleaning and import

First, import the two CSVs () into your own database. You may use what is available to you on `datasciencedb` or `datasciencedb2`. You may also create indexes and define keys if appropriate for the column(s) of your choice.

In the section below, you have the option to discuss any data cleaning and wrangling steps performed during this process. This is not a requirement and will not be assessed directly for grading; however, this may help to clarify to your reader exactly what was done, to make your work below more understandable.

In [99]:
import pandas as pd
import sqlalchemy as sq

# read in CSV as a dataframe
earlyON_forupload = pd.read_csv('earlyON_info_geom4326.csv')
tdsb_forupload = pd.read_csv('tdsb_info_geom4326.csv')

# connect to database
engine = sq.create_engine('mysql+mysqlconnector://gavinthomas_hurd:9zyd5IPmI7NOf@datasciencedb.ucalgary.ca/gavinthomas_hurd')

# write dataframe into a table
earlyON_forupload.to_sql("earlyon", engine, index=False, if_exists='replace')
tdsb_forupload.to_sql("tdsb", engine, index=False, if_exists='replace')

# test import success
earlyON_df = pd.read_sql_table("earlyon", engine)
tdsb_df = pd.read_sql_table("tdsb", engine)
# and print some information (not the entire table) about your second dataframe
display(earlyON_df.head())
display(tdsb_df.head())

from sqlalchemy import sql
conn = engine.connect()


_id service_system_manager  \
0    1        City of Toronto   
1    2        City of Toronto   
2    3        City of Toronto   
3    4        City of Toronto   
4    5        City of Toronto   

                                              agency  loc_id  \
0                Regent Park Community Health Centre   13650   
1  West Neighbourhood House O/a St. Christopher H...   14380   
2    West Scarborough Neighbourhood Community Centre   12554   
3                  Macaulay Child Development Centre   12562   
4                Regent Park Community Health Centre   13648   

                                    program_name languages  \
0  101 Spruce St EarlyON Child and Family Centre      None   
1           1033 EarlyON Child and Family Centre      None   
2           2555 EarlyON Child and Family Centre      None   
3  2700 Dufferin EarlyON Child and Family Centre      None   
4      38 Regent EarlyON Child and Family Centre      None   

  french_language_program indigenous_program programTypes serviceName  ...  \
0                    None               None         None     Drop-in  ...   
1                    None               None         None        None  ...   
2                    None               None         None        None  ...   
3                    None               None         None        None  ...   
4                    None               None         None        None  ...   

                     email      contact_fullname  \
0  Shani.Halfon@toronto.ca           Maleda Mulu   
1  Shani.Halfon@toronto.ca  Angela Elzinga Cheng   
2   Jene.Gordon@toronto.ca           Jessie Chen   
3      mmcdona5@toronto.ca        Sandra Aretusi   
4  Shani.Halfon@toronto.ca           Maleda Mulu   

                    contact_title               phone  \
0                 PROGRAM MANAGER  416-362-0805 X 230   
1  DIRECTOR OF COMMUNITY PROGRAMS        647-438-0038   
2             EARLYON COORDINATOR        416-266-8289   
3                      SUPERVISOR        416-789-7441   
4                 PROGRAM MANAGER  416-362-0805 X 230   

                 contact_email  \
0    maledam@regentparkchc.org   
1          angelael@westnh.org   
2            jessiec@wsncc.org   
3  saretusi@macaulaycentre.org   
4    maledam@regentparkchc.org   

                                         dropinHours  \
0                Wednesday: 9:00 a.m. - 11:30 a.m.     
1                                               None   
2  Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p...   
3  Monday: 10:00 a.m. - noon  ; 3:30 p.m. - 6:00 ...   
4  Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - ...   

                                     registeredHours virtualHours  \
0                 Thursday: 9:00 a.m. - 11:30 a.m.            NaN   
1                                               None          NaN   
2  Monday: 10:00 a.m. - 11:00 a.m.  ; 1:00 p.m. -...          NaN   
3  Tuesday: 10:00 a.m. - noon   | Thursday: 10:00...          NaN   
4  Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - ...          NaN   

                                            geometry  centre_type  
0  {'type': 'MultiPoint', 'coordinates': [[-79.36...       Centre  
1  {'type': 'MultiPoint', 'coordinates': [[-79.41...       Centre  
2  {'type': 'MultiPoint', 'coordinates': [[-79.27...       Centre  
3  {'type': 'MultiPoint', 'coordinates': [[-79.45...       Centre  
4  {'type': 'MultiPoint', 'coordinates': [[-79.36...       Centre  

[5 rows x 35 columns]

_id  ID                             SCH_NAME                    ADDRESS  \
0    1   1       Thorncliffe Park Public School  80 Thorncliffe Park Drive   
1    2   2              Highfield Junior School       85 Mount Olive Drive   
2    3   3       Victoria Village Public School           88 Sweeney Drive   
3    4   4               Grenoble Public School           9 Grenoble Drive   
4    5   5  Manhattan Park Junior Public School         90 Manhattan Drive   

          CITY POSTAL_CODE MET_PANEL_ID  ADDRESS_POINT_ID  ADDRESS_NUMBER  \
0    East York     M4H 1K3            E           3829444              80   
1    Etobicoke     M9V 2C9            E           1020028              85   
2   North York     M4A 1T7            E            566907              88   
3   North York     M3C 1C3            E            523752               9   
4  Scarborough     M1R 3V8            E            359023              90   

      LINEAR_NAME_FULL  ...                      PLACE_NAME GENERAL_USE_CODE  \
0  Thorncliffe Park Dr  ...  Thorncliffe Park Public School           115001   
1       Mount Olive Dr  ...         Highfield Public School           115001   
2           Sweeney Dr  ...  Victoria Village Public School           115001   
3          Grenoble Dr  ...          Grenoble Public School           115001   
4         Manhattan Dr  ...                  Manhattan Park           115001   

  CENTRELINE_ID  LO_NUM  LO_NUM_SUF  HI_NUM  HI_NUM_SUF  LINEAR_NAME_ID  \
0       3829449      80         NaN     NaN         NaN             354   
1        906730      85         NaN     NaN         NaN            2145   
2        442884      88         NaN     NaN         NaN            6834   
3      30093281       9         NaN     NaN         NaN            5756   
4        109829      90         NaN     NaN         NaN            8407   

   OBJECTID                                           geometry  
0         1  {'type': 'MultiPoint', 'coordinates': [[-79.34...  
1         2  {'type': 'MultiPoint', 'coordinates': [[-79.58...  
2         3  {'type': 'MultiPoint', 'coordinates': [[-79.31...  
3         4  {'type': 'MultiPoint', 'coordinates': [[-79.33...  
4         5  {'type': 'MultiPoint', 'coordinates': [[-79.29...  

[5 rows x 22 columns]

## Part A: Warm-up Questions (10 marks)

Answer the questions below, including any queries you used where necessary. Not all questions will necessarily require a SQL query for a correct response. You may wish to use as a source the references which are already provided as part of this notebook.

First, let's look at the Toronto District School Board Data.

1. How many schools are included in this file? **(1 mark)**


2.  While not all columns are equally interesting, let's focus on a few columns. Name three columns which could be used as a primary key for this dataset. **(3 marks)**

 
3. How would you describe the difference between the CITY and the MUNICIPALITY column? (Hint: You may wish to use information [at this link](https://www.toronto.ca/city-government/accountability-operations-customer-service/access-city-information-or-records/city-of-toronto-archives/using-the-archives/research-by-topic/resources-on-former-municipalities/) as a starting point **(2 marks)**

In [100]:
#1. Number of schools

output = conn.execute(sql.text(''' -- sql 
                               SELECT COUNT(DISTINCT sch_name) FROM tdsb 
                               WHERE sch_name IS NOT NULL;
                               '''))
print(output.fetchall())

#585 unique schools

[(585,)]


1. Based on the above SQL query, there are 585 distinct schools in the file.
2. As there are the same number of records in the dataset as their are unique schools, we each entry in the dataset cooresponds to a distinct school. Based on this finding, the school name (*sch_name*), address (*ADDRESS_FULL*), and municipality (*MUNICIPALITY*) could serve as a primary key.
3. It appears that the *CITY* column refers to the same geospatial locations as the *MUNICIPALITY* column, but the former contains the areas name prior to their conversion into a municipality of the Greater Toronto Area.

Next, let's look at the EarlyON table. 

4. How many different programs in total are listed in this dataset? **(1 mark)**


5. Are there any programs without websites listed? **(1 mark)**


6. Which columns would be suitable primary keys for this table? **(1 mark)**


7. Which major_intersection is listed for the most programs (and is not null)? Include the name of the intersection with the number of services. **(1 mark)**

In [101]:
#4. Number of programs
output = conn.execute(sql.text(''' -- sql 
                               SELECT COUNT(DISTINCT program_name) FROM earlyon 
                               WHERE program_name IS NOT NULL;
                               '''))
print(output.fetchall())

#253 unique programs

#5. Programs without website
output = conn.execute(sql.text(''' -- sql 
                               SELECT COUNT(DISTINCT program_name) FROM earlyon 
                               WHERE website IS NULL;
                               '''))
print(output.fetchall())
#68 programs without website

#7. Major intersection associated with most programs
output = conn.execute(sql.text(''' -- sql 
select major_intersection, COUNT(program_name)
from earlyon
group by major_intersection
order by COUNT(program_name) desc
LIMIT 2;
                               ;
                               '''))
print(output.fetchall())
#King St W/shaw St appears to be the most common non-null major intersection, 
# #although with a count of 1 it is likley tied with all other non-null intersections.

[(253,)]
[(68,)]
[(None, 219), ('King St W/shaw St', 1)]


4. Based upon the above query, there are 253 unique programs in the dataset.
5. There appears to be 68 programs that do not have an associated website.
6. The program names (*program_name*) column appear to be a good candidate as a primary key, however there are more records than unique values (as seen in q4). Therefore the *program_name* column might best be used in combination with the *_id* field to act as a primary key. Latly, the *address* in combination with the *_id* field could also be used as a primary key.
7. From the final SQL query result (above) we see that the *major_intersection* value that is associated with the most programs is actually *NULL*. The greatest non-null value is *King St W/shaw St*, however it only has a value of 1 and therefore is likley tied with many other major intersections.

## Part B: SQL with multiple tables (13 marks)


How many French-language EarlyON programs are currently operating in schools, and in what municipalities? **(2 marks)**

Provide a breakdown of schools offering EarlyON programs, by school type (for example, elementary, or secondary). include the ID for both the EarlyON program and the school.  **(2 marks)**

List all schools offering EarlyON programs which do not belong to the Toronto District School Board. **(1 mark)**

List all schools belonging to the Toronto District School Board which do not offer EarlyON programs **(1 mark)**

Out of all programs offered, what percentage of programTypes (Drop-in, Registered, Virtual) are offered by the EarlyON programs? Does this differ for programs housed in TDSB schools, compared to those which are not? **(2 marks)**

Prepare a list of community information in a single table, as follows: **(5 marks)**
- All EarlyOn programs should be listed, using the name of the program, and the full address.
- Where an EarlyON is hosted at a TDSB school, include the municipality, place name, and whether the school is an elementary school or secondary school.
- Any TDSB school that does not host an EarlyON program should be listed, using the address, municipality and place name.

In [96]:
#How many French-language EarlyON programs are currently operating in schools, and in what municipalities? 

output = conn.execute(sql.text(''' -- sql 
SELECT t.municipality, e.address FROM
(select french_language_program, `address`
from earlyon
WHERE french_language_program = 'Yes') as e
inner join
(select municipality, 'address'
FROM tdsb) as t
ON e.address = t.address;
                               '''))
print(output.fetchall())
#3 french language programs, none are operating in schools

OperationalError: (mysql.connector.errors.OperationalError) MySQL Connection not available.
[SQL:  -- sql 
SELECT t.municipality, e.address FROM
(select french_language_program, `address`
from earlyon
WHERE french_language_program = 'Yes') as e
inner join
(select municipality, 'address'
FROM tdsb) as t
ON e.address = t.address;
                               ]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [51]:
#Provide a breakdown of schools offering EarlyON programs, by school type (for example, elementary, or secondary). 
#include the ID for both the EarlyON program and the school.

output = conn.execute(sql.text(''' -- sql 
select e._id, t.id, t.sch_name, CASE
        WHEN sch_name LIKE '%high%' or sch_name LIKE '%secondary%' or sch_name LIKE '%senior%' THEN 'Secondary'
        WHEN sch_name LIKE '%middle%' THEN 'Middle'   
        WHEN sch_name LIKE '%elementary%' or sch_name LIKE  '%primary%' or sch_name LIKE  '%junior%' THEN 'Elementary'                                                           
        ELSE 'unknown'
    END as class from
(select `address`, _id
from earlyon) as e
inner join
(select `address`, sch_name, id
from tdsb) as t
ON e.address = t.address;
                               '''))
for i in output.fetchall():
    print(i)

(93, 220, 'H A Halbert Junior Public School', 'Elementary')
(88, 460, 'George Webster Elementary School', 'Elementary')
(13, 492, 'Agnes Macphail Public School', 'unknown')
(22, 501, 'Banting and Best Public School', 'unknown')
(172, 502, 'Port Royal Public School', 'unknown')
(141, 505, 'Military Trail Public School', 'unknown')
(136, 538, 'Market Lane Junior and Senior Public School', 'Secondary')
(253, 539, 'Yorkwoods Public School', 'unknown')


In [76]:
#List all schools offering EarlyON programs which do not belong to the Toronto District School Board.
output = conn.execute(sql.text(''' -- sql 
select school_name FROM
earlyon
where school_name not in (
SELECT distinct(sch_name) from tdsb);
                               '''))
for i in output.fetchall():
    print(i)



('BRUCE JUNIOR PUBLIC SCHOOL',)
('CARLETON VILLAGE JUNIOR AND SENIOR PUBLIC SCHOOL',)
('ACADÉMIE ALEXANDRE-DUMAS',)
('ÉCOLE ÉLÉMENTAIRE GABRIELLE-ROY',)
('CHARLES E WEBSTER JUNIOR PUBLIC SCHOOL',)
('DR RITA COX - KINA MINOGOK PUBLIC SCHOOL',)
('EASTVIEW JUNIOR PUBLIC SCHOOL',)
('ETOBICOKE SECONDARY ALTERNATIVE SCHOOL',)
('HOLY SPIRIT CATHOLIC SCHOOL',)
("D'ARCY MCGEE CATHOLIC SCHOOL",)
('KNOB HILL JUNIOR PUBLIC SCHOOL',)
('MORSE',)
('OUR LADY OF THE ASSUMPTION CATHOLIC SCHOOL',)
('RODEN JUNIOR PUBLIC SCHOOL',)
('ST. PAUL CATHOLIC SCHOOL',)
('SPRUCECOURT JUNIOR PUBLIC SCHOOL',)
('ST. AIDAN CATHOLIC SCHOOL',)
('ST. ALBERT CATHOLIC SCHOOL',)
('ST. ANGELA CATHOLIC SCHOOL',)
('ST. ANTHONY CATHOLIC SCHOOL',)
('ST. BARBARA CATHOLIC SCHOOL',)
('ST. BARNABAS CATHOLIC SCHOOL',)
('ST. CHARLES GARNIER CATHOLIC SCHOOL',)
('ST. DOROTHY CATHOLIC SCHOOL',)
('ST. FRANCIS DE SALES CATHOLIC SCHOOL',)
('ST. HELEN CATHOLIC SCHOOL',)
('ST. JOHN XXIII CATHOLIC SCHOOL',)
('ST. LEO CATHOLIC SCHOOL',)
('ST. MAR

In [85]:
#List all schools belonging to the Toronto District School Board which do not offer EarlyON programs

output = conn.execute(sql.text(''' -- sql 
SELECT t.sch_name
FROM tdsb t
LEFT JOIN earlyon e ON t.sch_name = e.school_name
WHERE e.school_name IS NULL;
                               '''))
for i in output.fetchall():
    print(i)


('Thorncliffe Park Public School',)
('Victoria Village Public School',)
('Manhattan Park Junior Public School',)
('Brian Public School',)
('North Preparatory Junior Public School',)
('Bliss Carman Senior Public School',)
('Bloordale Middle School',)
('Courcelette Public School',)
('Derrydown Public School',)
('Maplewood High School',)
('George B Little Public School',)
('John G Althouse Middle School',)
('Warren Park Junior Public School',)
('Humbercrest Public School',)
('Cliffwood Public School',)
('Cedarvale Community School',)
('Greenland Public School',)
('Victoria Park Collegiate Institute',)
('White Haven Public School',)
('Seventh Street Junior School',)
('Norseman Junior Middle School',)
('Lillian Public School',)
('Riverdale Collegiate Institute',)
('King Edward Junior and Senior Public School',)
('Bloor Collegiate Institute',)
('Monarch Park Collegiate Institute',)
('C R Marchant Middle School',)
('Central Etobicoke High School',)
('Weston Collegiate Institute',)
('Contact A

In [84]:
#Out of all programs offered, what percentage of programTypes (Drop-in, Registered, Virtual) are offered by the EarlyON programs? 
#Does this differ for programs housed in TDSB schools, compared to those which are not?

#Get lengths of total early
lengths = conn.execute(sql.text(''' -- sql 
SELECT e.e_count, et.et_count FROM
(SELECT COUNT(*) as e_count
FROM earlyon) as e
JOIN
(SELECT COUNT(*) as et_count
FROM earlyon 
WHERE school_name NOT IN (SELECT DISTINCT(sch_name) FROM tdsb)) as et;
                               '''))
print(lengths.fetchall())

output = conn.execute(sql.text(''' -- sql 
SELECT `drop`.drop_perc, `virtual`.virtual_perc, `registered`.registered_perc FROM
(SELECT (COUNT(dropinHours)*100 / 254) as drop_perc
FROM earlyon 
WHERE dropinHours IS NOT NULL) as `drop`
JOIN
(SELECT (COUNT(virtualHours)*100 / 254) as virtual_perc
FROM earlyon 
WHERE virtualHours IS NOT NULL) as `virtual`
JOIN
(SELECT (COUNT(registeredHours)*100 / 254) as registered_perc
FROM earlyon 
WHERE registeredHours IS NOT NULL) as `registered`;
                               '''))
for i in output.fetchall():
    print(i)

output2 = conn.execute(sql.text(''' -- sql 
SELECT `drop`.drop_perc, `virtual`.virtual_perc, `registered`.registered_perc FROM
(SELECT (COUNT(dropinHours)*100 / 34) as drop_perc
FROM earlyon 
WHERE dropinHours IS NOT NULL
    AND school_name NOT IN (SELECT DISTINCT(sch_name) FROM tdsb)) as `drop`
JOIN
(SELECT (COUNT(virtualHours)*100 / 34) as virtual_perc
FROM earlyon 
WHERE virtualHours IS NOT NULL 
    AND school_name NOT IN (SELECT DISTINCT(sch_name) FROM tdsb)) as `virtual`
JOIN
(SELECT (COUNT(registeredHours)*100 / 34) as registered_perc
FROM earlyon 
WHERE registeredHours IS NOT NULL
    AND school_name NOT IN (SELECT DISTINCT(sch_name) FROM tdsb)) as `registered`;
                               '''))
for i in output2.fetchall():
    print(i)

#From this we see that the percentage of virtual programtypes are zero for all of the programs and only the ones housed in TDSB schools. 
# In contrast, we see that drop in hours make up 89% of the total offered programs, but 100% of those housed in TDSB schools.
#The opposite trend is observed in registered hours, with 25% of total programs being allocated to this type, but only 3% of those occuring in TDSB school.
#The fact that both the aggregate percent of total programs offered by EarlyON and programs offered exclusively in TDSB schools is greater than 100% indicates that there is an overlap
#between drop-in and registered programs (i.e. they occur simultaneously)


[(254, 34)]
(Decimal('89.3701'), Decimal('0.0000'), Decimal('25.1969'))
(Decimal('100.0000'), Decimal('0.0000'), Decimal('2.9412'))


In [95]:
#Prepare a list of community information in a single table, as follows:
#- All EarlyOn programs should be listed, using the name of the program, and the full address.
#- Where an EarlyON is hosted at a TDSB school, include the municipality, place name, and whether the school is an elementary school or secondary school.
#- Any TDSB school that does not host an EarlyON program should be listed, using the address, municipality and place name.

sql_query = pd.read_sql_query (
    '''
SELECT * FROM
(SELECT e.program_name , e.full_address, t.sch_name, t.municipality, t.place_name, t.class FROM
    (SELECT program_name, full_address, school_name
    FROM earlyon) as e
    LEFT JOIN
    (SELECT sch_name, municipality, place_name, (CASE
        WHEN sch_name LIKE '%high%' or sch_name LIKE '%secondary%' or sch_name LIKE '%senior%' THEN 'Secondary'
        WHEN sch_name LIKE '%elementary%' or sch_name LIKE  '%primary%' or sch_name LIKE  '%junior%' THEN 'Elementary'                                                           
        ELSE 'unknown'
        END) as class FROM tdsb) as t
	ON e.school_name = t.sch_name) as earlyon_tdsb
    UNION
    (SELECT 'NA' as program_name, address_full as full_address, sch_name, municipality, place_name, (CASE
        WHEN sch_name LIKE '%high%' or sch_name LIKE '%secondary%' or sch_name LIKE '%senior%' THEN 'Secondary'
        WHEN sch_name LIKE '%elementary%' or sch_name LIKE  '%primary%' or sch_name LIKE  '%junior%' THEN 'Elementary'                                                           
        ELSE 'unknown'
        END) as class 
    FROM tdsb)
    ORDER BY full_address
    ''',
    conn)
display(sql_query)

program_name                   full_address  \
0                                          NA                 1 Danforth Ave   
1                                          NA                    1 Hanson St   
2                                          NA                    1 Hanson St   
3                                          NA                     1 Ralph St   
4                                          NA                   1 Selwyn Ave   
..                                        ...                            ...   
834                                        NA               99 Mountview Ave   
835                                        NA                    990 Jane St   
836  Roseland EarlyON Child and Family Centre  990 Jane St, York, ON M6N 4E2   
837                                        NA             991 St Clair Ave W   
838                                        NA                 994 Carlaw Ave   

                                sch_name    municipality  \
0                  CALC Secondary School  former Toronto   
1      Monarch Park Collegiate Institute  former Toronto   
2              School of Life Experience  former Toronto   
3             C R Marchant Middle School            York   
4               Selwyn Elementary School       East York   
..                                   ...             ...   
834  Mountview Alternative Junior School  former Toronto   
835       Roselands Junior Public School            York   
836       Roselands Junior Public School            York   
837         Oakwood Collegiate Institute  former Toronto   
838               Westwood Middle School       East York   

                            place_name       class  
0    City Adult Learning Centre (Calc)   Secondary  
1              Monarch Park Collegiate     unknown  
2              Monarch Park Collegiate     unknown  
3         C. R. Marchant Middle School     unknown  
4             Selwyn Elementary School  Elementary  
..                                 ...         ...  
834         Keele Street Public School  Elementary  
835     Roselands Junior Public School  Elementary  
836     Roselands Junior Public School  Elementary  
837       Oakwood Collegiate Institute     unknown  
838                      Westwood Park     unknown  

[839 rows x 6 columns]

## Part C: Evaluating your results  (7 marks)


**Question 1 (2 marks)**

The two datasets provided for this assignment offer a limited set of data, for different purposes. How do you think the use of these datasets might differ?








The tdsb dataset appears to be a repository of school locations and their attributes. This would be useful in geopsatial analyses such as the distribution of school densities/accessibility by region in the GTA. On the other hand, the EarlyON dataset contains information about the time and location of various community programs; such a dataset would be more geared towards developing a public-use application about when and where to access community services.

**Question 2 (1 mark)**

One thing you may have had consider is your selection of columns from both datasets to use as a key for any joins you performed. Discuss your reasoning behind your choice of key. If you don't think you had a reason in particular, then name another pair of colums which could have been used to execute your joins.

The choice of primary key for joins was often determined by the question itself. In several instances, the goal was to obtain information from the tdsb dataset for all instances where the school was common to the EarlyON dataset. For these cases, it made sense to structure the query on the school_name attribute such that the join itself would filter the tdsb dataset to the desired subset. After this, the relevant information could easily be extracted from the subset/joined dataset.

**Question 3 (4 marks)**

It is possible to download both datasets as GeoJSON files rather than as CSVs. Imagine that we have loaded these GeoJSON files into MongoDB instead of a relational database.

Pick one of the queries from Part B to discuss. Do you think it is more difficult to retrieve the information requested for this query from the pair of relational database tables provided to you, or from a MongoDB collection set up as described? Explain why or why not. 

For the final question in Part b that asked: *"Prepare a list of community information in a single table..."*, I imagine that parts of it are well suited towards a GeoJSON/MongoDB collection, while other aspects are not. The key:value format of a JSON based query would allow the efficient extraction and combination of the schools in the tdsb collection that offer earlyON programs. However, I am less confident in MongoDB's ability to create the new category of *class* (e.g. elementary or secondary) across different levels in the hierarchy. Additionally, I am not sure if MongoDB would be able to effectively populate missing data points for attributes that are not shared in part of the query (i.e. the NAs in the program_name column for tdsb schools that did not host EarlyON programs).
Unfortunately, much of the above is based solely on my admitedly vague understanding of MongoDB. I do plan on broadening my DBMS competency with experrience in MongoDB, but for the time being I think it is wise to assume that my understanding of MongoDB is limited.

## Part E: Reflection (5 marks)

In a brief paragraph for each (no more than 500 words total), answer the following:


1) Identify a skill or concept which you are now more knowledgable or comfortable with now, compared to at the start of DATA 604. 


2) What best helped you to learn this skill or concept? Was it something covered in class, part of an assignment or project, or another resource?


3) Based upon what you have learned, where do you see an opportunity to continue to develop your understanding of this skill? 




1. Following the past few months, my abilities in SQL syntax and knowledge of Databses has grown enormously. At the start of this course I could not have confidently said what the advantages of a designated databse were. Now I understand the invaluable speed and security benefits provided by databsase management systems, and I could even set up a very basic one. Additionally, I can confidently perform basic SQL queries, and I believe I have the tools to learn how to structure complex queries.
2. For me, nothing can beat hands-on experience. I found the assignments and the projects to be the best way to further my understanding of working with 'big data.' As a side not, I may actually have learned the most when things went wrong. For example, when the UofC db server crashed, I created a local server which was a great learning opportunity. Similarly, during the project when I tried to join tables based on geospatial attributed and the computation time proved to be too much, I learned how to more efficiently structure *joins* by joining at two different levels of specificity, and consequently decreasing the 'Big O.'
3. As mentioned in the above question, I have limited experience with other DBMS. For me, obtianing hands-on experience with MongoDB and other systems would be hugely beneficial. This would be best done through a project, which might mean that it would be good for me to find a way to complete an upcoming project in the MDSA program through the use of a different DBMS. 

## References

Both datasets used in this Assignment are licensed under the Open Government License - City of Toronto.

EarlyON child and Family Centres [online], 2023. Open Data (City of Toronto). Available from: https://open.toronto.ca/dataset/earlyon-child-and-family-centres/ [Accessed 23 Nov 2023].

Toronto District School Board Locations [online], 2023. Open Data (City of Toronto). Available from: https://open.toronto.ca/dataset/toronto-district-school-board-locations/ [Accessed 23 Nov 2023].
